version: '3.8'
networks:
  monitoring:
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - $PWD/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - $PWD/config/prometheus/targets.json:/etc/prometheus/targets.json
      - prometheus_data:/prometheus
    networks:
      - monitoring
    ports:
      - 9090:9090
  snmp-exporter:
    image: prom/snmp-exporter
    container_name: snmp-exporter
    volumes:
      - $PWD/config/snmp-exporter/snmp.yml:/etc/snmp_exporter/snmp.yml
    networks:
      - monitoring
    ports:
      - 9116:9116
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - $PWD/config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
    ports:
      - 3000:3000
