[[servers]]
host = ""
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false
bind_dn = ""
bind_password = ''
search_filter = ""
search_base_dns = [""]

[servers.attributes]
member_of = "memberOf"
email =  "mail"

# [[servers.group_mappings]] omitted for clarity