global:
  scrape_interval: 1m
scrape_configs:
  - job_name: 'snmp'
    file_sd_configs:
    - files:
      - 'targets.json'
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116 